// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/list": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Crypt"
                ],
                "summary": "Получение информации по криптовалютам",
                "operationId": "list-crypto",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Название биржы",
                        "name": "cryptoexchange_name",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "Цена снизу",
                        "name": "price_from",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "Цена сверху",
                        "name": "price_to",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Ёршик",
                        "name": "find_brush",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "данные по криптовалюте",
                        "schema": {
                            "$ref": "#/definitions/model.Crypto"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.Crypto": {
            "type": "object",
            "properties": {
                "cryptocurrencyId": {
                    "type": "integer"
                },
                "cryptocurrencyTicker": {
                    "type": "string"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.DataCrypto"
                    }
                }
            }
        },
        "model.DataCrypto": {
            "type": "object",
            "properties": {
                "cryptoExchangeName": {
                    "type": "string"
                },
                "data_olhcv": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "data_order_book": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "spread": {
                    "type": "number"
                }
            }
        }
    },
    "tags": [
        {
            "description": "Криптовалюты",
            "name": "Crypt"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "localhost:8050",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Crypt API",
	Description:      "Сервис по получению инфы по криптовалютам с бирж",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
